# Generated by Django 3.2.7 on 2021-09-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mass', models.IntegerField(blank=True, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=25, null=True)),
                ('skin_color', models.CharField(blank=True, max_length=25, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=25, null=True)),
                ('birth_year', models.CharField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
