# Generated by Django 3.2.7 on 2021-09-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characters',
            options={'verbose_name': 'Characters'},
        ),
        migrations.AlterField(
            model_name='characters',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characters',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
